### ISSUE TITLE
Reference genome RNA-seq

### ISSUE THREAD

**Issue by BiotechPedro** [biodev/beataml2.0_data#1]
Hi!

First of all, congrats on the amazing data and study you generated. An incredibly useful resource, sincerely!

I have downloaded the data, and for the RNA-seq it is said in the Cancer Cell 2022 article that the gene-level RNA-seq counts were generated as in the previous manuscript. Therefore, I have checked the Nature 2018 paper and have realised that the reference genome used was GRCh37.

Should I understand that the data analysed in the second manuscript and [available for downloading](https://biodev.github.io/BeatAML2/) were aligned to GRCh37.

Thanks,

Pedro

**Comment by dbottomly** [comment]
Hi @BiotechPedro, yes GRCh37 was used for all alignments.  RNASeq and mutation calls are also available aligned to GRCh38 from the [Genomic Data Commons](https://gdc.cancer.gov/about-data/publications/BEATAML1-0-COHORT-2022).

**Comment by BiotechPedro** [comment]
Ah yes! Thank you for the confirmation!!
