### ISSUE TITLE
Is it free to use these data OR permission required? 

### ISSUE THREAD

**Issue by rainoffallingstar** [biodev/beataml2.0_data#2]
Hi, I‘m a medical student now working in Hematology, and performing some research projects in AML. I’m wondering if it is free to use these data （beataml2.0） or a permission of access  is required？

**Comment by dbottomly** [comment]
Sorry for the very long delay. Yes free to use per the terms of [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/deed.en)
